[package]
name = "ferrodb-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
bincode = "1.3.3"
ron = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
