[package]
name = "ferrodb-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.0.5"
ferrodb-page = { path = "../ferrodb-page" }
ferrodb-util = { path = "../ferrodb-util" }
parking_lot = "0.11.2"
thiserror = "1.0.30"
