[package]
name = "ferrodb-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
ferrodb-protocol = { path = "../ferrodb-protocol" }
erased-serde = "0.3.16"